# Solar Time

In [3]:
import numpy as np

In [34]:
s_200 = [200000] + np.arange(201000,219001,1500).tolist()
s_120 = [200000,202000,203000,204000,205000,206000,207000,208000,209000,210000,212000,213000,214000,215000,216000,217000,218000,219000,220000]
s_100 = [200000,202000,203000,204000,205000,206000,207000,208000,209000,210000,212000,213000,214000,215000,216000,217000,218000,219000,220000]
s_50 = [200000] + np.arange(201000,228001,1500).tolist()
s_30 = [200000] + np.arange(201000,228001,1500).tolist()

In [3]:
s_30

[200000,
 201000,
 202500,
 204000,
 205500,
 207000,
 208500,
 210000,
 211500,
 213000,
 214500,
 216000,
 217500,
 219000,
 220500,
 222000,
 223500,
 225000,
 226500,
 228000]

In [43]:
solar_time_30 =  np.array([65201.65266, 65435.77086, 65753.62258, 66048.60092, 66353.54135, \
                           66654.06231,66946.93533,67263.13462,67561.38728,67865.81313,68155.12146, \
                          68464.44211,68791.25731, 69099.45867,69415.71192,69740.24136,70051.72283,\
                          70400.00559,70725.78341,71025.90899 ])

In [44]:
test = solar_time_30 - 65201.65266

In [45]:
test/60

array([ 0.        ,  3.90197   ,  9.19949867, 14.11580433, 19.19814483,
       24.2068275 , 29.0880445 , 34.35803267, 39.32891033, 44.4026745 ,
       49.22448   , 54.37982417, 59.82674417, 64.9634335 , 70.234321  ,
       75.643145  , 80.83450283, 86.6392155 , 92.06884583, 97.07093883])

In [60]:
np.around(np.diff(test/60),decimals=1)

array([3.9, 5.3, 4.9, 5.1, 5. , 4.9, 5.3, 5. , 5.1, 4.8, 5.2, 5.4, 5.1,
       5.3, 5.4, 5.2, 5.8, 5.4, 5. ])

In [16]:
np.mean(np.diff(test/60))

5.108996780701752

In [17]:
np.std(np.diff(test/60))

0.3670085640387259

In [49]:
solar_time_50 =  np.array([63160.95925,63360.73656,63648.35059,63945.89133,64231.39668,64512.54837,\
                          64802.45891, 65079.71999, 65353.28023,65633.08881,65931.05376,66230.90372,66512.92356,\
                          66802.14607, 67087.88783, 67372.30172, 67654.43993, 67954.22947, 68251.23911, 68525.62667])

In [50]:
test50 = solar_time_50 - 63160.95925

In [51]:
test50/60

array([ 0.        ,  3.32962183,  8.123189  , 13.08220133, 17.84062383,
       22.52648533, 27.35832767, 31.97934567, 36.538683  , 41.20215933,
       46.16824183, 51.16574117, 55.86607183, 60.686447  , 65.44880967,
       70.18904117, 74.89134467, 79.887837  , 84.83799767, 89.41112367])

In [59]:
np.around(np.diff(test50/60),decimals=1)

array([3.3, 4.8, 5. , 4.8, 4.7, 4.8, 4.6, 4.6, 4.7, 5. , 5. , 4.7, 4.8,
       4.8, 4.7, 4.7, 5. , 5. , 4.6])

In [30]:
np.mean(np.diff(test50/60))

4.7058486140350855

In [31]:
np.std(np.diff(test50/60))

0.3514912821788088

In [ ]:
# 100G restart is every 7 minutes, most likely so is the 120G, but cannot check as no anls.dat file, maybe need to read in the headers

In [36]:
sim_dir = '/data/sun/przybylski/tino_restart_forjonas_10hr/100G_restart/100G_v2/3D/'
times = []
for i in s_100[1:]:
    header = np.loadtxt(sim_dir + f'Header.{i}')
    print(header[6])
    times.append(header[6])

455.792187
677.146542
913.504394
1137.084033
1365.557079
1595.596883
1822.100988
2048.169563
2270.822862
2707.258905
2923.861287
3144.724012
3363.961751
3580.009757
3802.022837
4022.66476
4245.506356
4477.177629


In [53]:
times = np.array(times)
np.around(np.diff(times/60),decimals=1)

array([3.8, 3.8, 3.8, 3.7, 3.6, 3.6, 3.7, 3.6, 7.2, 3.8, 3.8, 3.8, 3.8,
       3.6, 3.6, 3.6, 3.7])

In [41]:
sim_dir = '/data/sun/przybylski/tino_restart_forjonas_10hr/120G_restart/120G/3D/'
times = []
for i in s_120[1:]:
    header = np.loadtxt(sim_dir + f'Header.{i}')
    print(header[6])
    times.append(header[6])

434.087007
661.504363
887.258673
1116.255589
1337.612335
1551.005529
1768.042025
1988.417825
2202.258383
2637.144848
2864.198852
3090.896415
3321.07604
3547.263874
3763.583533
3980.819319
4199.484975
4420.521394


In [42]:
times = np.array(times)
np.diff(times/60)

array([3.79028927, 3.76257183, 3.81661527, 3.6892791 , 3.55655323,
       3.61727493, 3.67293   , 3.5640093 , 7.24810775, 3.7842334 ,
       3.77829272, 3.83632708, 3.76979723, 3.60532765, 3.62059643,
       3.6444276 , 3.68394032])

In [33]:
s_200

[200000,
 201000,
 202500,
 204000,
 205500,
 207000,
 208500,
 210000,
 211500,
 213000,
 214500,
 216000,
 217500,
 219000]

In [54]:
solar_time_200 =  np.array([61965.68342,62143.37903,62411.03944,62676.61265,62948.42949,63221.84556,63488.60674,\
                           63766.42989,64041.23195,64310.45527,64579.56043,64848.59974,65118.31854,65392.06307])

In [55]:
test200 = solar_time_200 - 61965.68342

In [56]:
test200/60

array([ 0.        ,  2.9615935 ,  7.42260033, 11.8488205 , 16.37910117,
       20.93603567, 25.38205533, 30.01244117, 34.5924755 , 39.07953083,
       43.56461683, 48.04860533, 52.54391867, 57.1063275 ])

In [58]:
np.around(np.diff(test200/60),decimals=2)

array([2.96, 4.46, 4.43, 4.53, 4.56, 4.45, 4.63, 4.58, 4.49, 4.49, 4.48,
       4.5 , 4.56])

In [43]:
np.mean(np.diff(test200/60))

4.392794423076917

In [44]:
np.std(np.diff(test200/60))

0.416883169894275

In [46]:
61965.68342/60/60

17.21268983888889

In [1]:
# check tanayveer's cubes

In [22]:
sim_dir = '/data/bhatia/jonas/G_30/3D/'
siter= ['079245','081486','083742','086038','088303','090538','092779','095011','097188','099413','101564','103737']
head = np.memmap(sim_dir + 'Header.079245',mode='r',dtype=np.int16)

In [23]:
head

memmap([12341,  8240, 13600, 12849,  8224, 12597,  8242, 12576, 12336,
        12336, 12336, 12334, 12336, 12336,  8240, 12576, 13623, 14391,
        12849, 13614, 12336, 12336,  8240, 12576, 13623, 14391, 12849,
        13614, 12336, 12336,  8240, 12576, 13363, 12340, 12334, 12336,
        12336,  8240, 12320, 12334, 13616, 13617,  8248, 12576, 12336,
        12336, 12336, 11824, 12336, 12336, 12336], dtype=int16)

In [24]:
header = 

In [28]:
header[6]

13440.0

In [29]:
times = []
for i in siter:
    header = np.loadtxt(sim_dir + f'Header.{i}')
    print(header[6])
    times.append(header[6])

13440.0
13740.0
14040.0
14340.0
14640.0
14940.0
15240.0
15540.0
15840.0
16140.0
16440.0
16740.0


In [30]:
sim_dir = '/data/bhatia/jonas/G_100/3D/'
siter= ['062302','064671','067043','069447','071858','074219','076639','079042','081434','083791','086170','088576']
times = []
for i in siter:
    header = np.loadtxt(sim_dir + f'Header.{i}')
    print(header[6])
    times.append(header[6])

7740.0
8040.0
8340.0
8640.0
8940.0
9240.0
9540.0
9840.0
10140.0
10440.0
10740.0
11040.0


In [32]:
sim_dir = '/data/bhatia/jonas/G_200/3D/'
siter= ['459704','462122','464531','466962','469389','471811','474220','476643','479085','481513','483915','486360']
times = []
for i in siter:
    header = np.loadtxt(sim_dir + f'Header.{i}')
    print(header[6])
    times.append(header[6])

169830.0
170130.0
170430.0
170730.0
171030.0
171330.0
171630.0
171930.0
172230.0
172530.0
172830.0
173130.0
